// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: filetransfer/filetransfer.proto

package filetransferconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	filetransfer "github.com/itsrobel/sync/internal/services/filetransfer"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "filetransfer.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceSendFileToServerProcedure is the fully-qualified name of the FileService's
	// SendFileToServer RPC.
	FileServiceSendFileToServerProcedure = "/filetransfer.FileService/SendFileToServer"
	// FileServiceValidateServerProcedure is the fully-qualified name of the FileService's
	// ValidateServer RPC.
	FileServiceValidateServerProcedure = "/filetransfer.FileService/ValidateServer"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	fileServiceServiceDescriptor                = filetransfer.File_filetransfer_filetransfer_proto.Services().ByName("FileService")
	fileServiceSendFileToServerMethodDescriptor = fileServiceServiceDescriptor.Methods().ByName("SendFileToServer")
	fileServiceValidateServerMethodDescriptor   = fileServiceServiceDescriptor.Methods().ByName("ValidateServer")
)

// FileServiceClient is a client for the filetransfer.FileService service.
type FileServiceClient interface {
	// rpc StreamFileChanges(stream FileChange) returns (stream FileChange) {}; // Bidirectional streaming for file changes
	// rpc SendFileToClient(FileRequest) returns (stream FileData) {};
	SendFileToServer(context.Context) *connect.ClientStreamForClient[filetransfer.FileData, filetransfer.ActionResponse]
	ValidateServer(context.Context, *connect.Request[filetransfer.ActionResponse]) (*connect.Response[filetransfer.ActionResponse], error)
}

// NewFileServiceClient constructs a client for the filetransfer.FileService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &fileServiceClient{
		sendFileToServer: connect.NewClient[filetransfer.FileData, filetransfer.ActionResponse](
			httpClient,
			baseURL+FileServiceSendFileToServerProcedure,
			connect.WithSchema(fileServiceSendFileToServerMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		validateServer: connect.NewClient[filetransfer.ActionResponse, filetransfer.ActionResponse](
			httpClient,
			baseURL+FileServiceValidateServerProcedure,
			connect.WithSchema(fileServiceValidateServerMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	sendFileToServer *connect.Client[filetransfer.FileData, filetransfer.ActionResponse]
	validateServer   *connect.Client[filetransfer.ActionResponse, filetransfer.ActionResponse]
}

// SendFileToServer calls filetransfer.FileService.SendFileToServer.
func (c *fileServiceClient) SendFileToServer(ctx context.Context) *connect.ClientStreamForClient[filetransfer.FileData, filetransfer.ActionResponse] {
	return c.sendFileToServer.CallClientStream(ctx)
}

// ValidateServer calls filetransfer.FileService.ValidateServer.
func (c *fileServiceClient) ValidateServer(ctx context.Context, req *connect.Request[filetransfer.ActionResponse]) (*connect.Response[filetransfer.ActionResponse], error) {
	return c.validateServer.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the filetransfer.FileService service.
type FileServiceHandler interface {
	// rpc StreamFileChanges(stream FileChange) returns (stream FileChange) {}; // Bidirectional streaming for file changes
	// rpc SendFileToClient(FileRequest) returns (stream FileData) {};
	SendFileToServer(context.Context, *connect.ClientStream[filetransfer.FileData]) (*connect.Response[filetransfer.ActionResponse], error)
	ValidateServer(context.Context, *connect.Request[filetransfer.ActionResponse]) (*connect.Response[filetransfer.ActionResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceSendFileToServerHandler := connect.NewClientStreamHandler(
		FileServiceSendFileToServerProcedure,
		svc.SendFileToServer,
		connect.WithSchema(fileServiceSendFileToServerMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceValidateServerHandler := connect.NewUnaryHandler(
		FileServiceValidateServerProcedure,
		svc.ValidateServer,
		connect.WithSchema(fileServiceValidateServerMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/filetransfer.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServiceSendFileToServerProcedure:
			fileServiceSendFileToServerHandler.ServeHTTP(w, r)
		case FileServiceValidateServerProcedure:
			fileServiceValidateServerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) SendFileToServer(context.Context, *connect.ClientStream[filetransfer.FileData]) (*connect.Response[filetransfer.ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("filetransfer.FileService.SendFileToServer is not implemented"))
}

func (UnimplementedFileServiceHandler) ValidateServer(context.Context, *connect.Request[filetransfer.ActionResponse]) (*connect.Response[filetransfer.ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("filetransfer.FileService.ValidateServer is not implemented"))
}
